### ISSUE TITLE
[Question] LazySentry.ts -  how does errorQueue work?

### ISSUE THREAD

**Issue by saint777** [Daniel15/LazySentry#1]
```
errorQueue.forEach(x => window.onerror?.(...x));
rejectionQueue.forEach(e => window.onunhandledrejection?.(e));
```

Hey Daniel, can you please comment this piece of code?
How does this work? I guess "Sentry Init" replaces window.onerror with its "global handlers"?

Couldn't find in source code of sentry-js

@Daniel15

**Comment by Daniel15** [comment]
Yes, Sentry attaches its own onerror handler. I think it's here, but I'm not entirely sure what the code is doing: https://github.com/getsentry/sentry-javascript/blob/ac3cf2023d577de920febd346b827020f6ca2e0c/packages/browser/src/integrations/globalhandlers.ts

I just noticed it as a user of the library - after loading it, there's an onerror handler, so I rely on that :smiley:  I didn't actually investigate how the Sentry JS code works.
